sudo: required
language: node_js
node_js:
- stable
cache:
  directories:
  - npm
  - node_modules
before_script:
- npm install
- npm install codecov mocha -g
env:
- CODECOV_TOKEN="ffa08c9e-7f21-4c51-9983-6fb4670cd246"
script:
- npm run lint
- npm run build:dist
- npm run test
after_success:
- bash <(curl -s https://codecov.io/bash) -t ffa08c9e-7f21-4c51-9983-6fb4670cd246
